config/routes.rb
Rails.application.routes.draw do

  unless Rails.env.production?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  mount API::Root => '/'

  root 'top#index'
  get '/term_of_use' => 'top#term_of_use'
  get '/privacy_policy' => 'top#privacy_policy'
  get '/special_commercial_code' => 'top#special_commercial_code'

  namespace :admin do
    get '/' => 'dashboards#index'
    get '/sign_in' => 'sessions#new'
    post '/sign_in' => 'sessions#create'
    get '/sign_out' => 'sessions#destroy'
    resources :dashboards, only: [:index]
    resources :admin_users, except: [:show]
    resources :users do
      resources :personal_identifications
      post :proxy_access, on: :member
    end
    resources :user_corps do
      resources :users, controller: 'users' do
        post :proxy_access, on: :member
      end
    end
    resources :information
    resources :corporations do
      resources :corporate_admin_users
      resources :user_contracts
      resources :plans
      resources :facilities, only: [] do
        member do
          get :events
        end
        resources :facility_plans, only: [:new, :create, :destroy]
        resources :facility_dropin_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources, format: 'json'
            get :events, format: 'json'
          end
        end
        resources :facility_temporary_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources
            get :events
          end
        end
        resources :facility_pack_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources
            get :events
          end
        end
      end
      resources :shops, except: [:index] do
        resources :facilities, except: [:index] do
          resources :facility_keys, except: [:index]
        end
      end
    end
    resources :reservations do
      collection do
        get :payment
        get :confirm
      end
    end
    resources :dropin_reservations do
      collection do
        get :payment
        get :confirm
      end
    end
    resources :billings, only: [:index, :show]
  end

  resource :user do
    collection do
      get 'new/:parent_token', to: 'users#new', as: 'new_parent_token'
      get 'tel', to: 'users#tel'
      post 'sms', to: 'users#sms'
      post 'sms_confirm', to: 'users#sms_confirm'
    end
  end
  get '/sign_in' => 'sessions#new'
  post '/sign_in' => 'sessions#create'
  get '/sign_out' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get :reminder
      post :post_reminder
      get 'reset_password/:token', to: 'sessions#reset_password', as: 'reset_password'
      patch 'update_password/:token', to: 'sessions#update_password', as: 'update_password'
    end
  end
  resources :shops, only: [:index, :show] do
    resources :facilities, only: [:new, :create], controller: 'shops/facilities'
  end
  get '/shops/:shop_id/facilities/:id/events' => 'shops/facilities#events'
  resources :facilities, only: [:index, :show]
  resources :reservations, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :price
      get :dropin_spot
      get :spot
      post :confirm
      get :confirm
      post :credit_card
      get :thanks
    end
  end
  resource :personal_identification
  resources :dropin_reservations, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :plan
      get :dropin_spot
      post :confirm
      get :confirm
      post :credit_card
      get :thanks
    end
  end
  resources :plans
  resource :credit_card, only: [:new, :create, :show, :edit, :update]
  resources :invitations, only: [:index, :new, :create]
  resources :information, only: [:index, :show]

  post '/fetch_corporation_ids' => 'corporations#fetch_corporation_ids'

  namespace :corporation do
    get '/:corporation_token/users/new' => 'users#new', as: 'new_user'
    post '/:corporation_token/users' => 'users#create', as: 'user'
  end

  # 法人メニュー
  namespace :corporation_manage do
    root 'dashboards#index'
    resources :user_contracts
    resources :shops, only: %i[new show edit create update destroy] do
      resources :facilities, only: %i[new show edit create update destroy] do
        get :facility_events, on: :member
        resources :facility_keys, only: %i[new show edit create update destroy]
        resources :facility_temporary_plans, only: %i[index new edit create update destroy]
        resources :facility_temporary_plan_prices, only: %i[index]
        resources :facility_dropin_plans, only: %i[index new edit create update destroy]
        resources :facility_dropin_sub_plans, only: %i[index]
        resources :facility_pack_plans, only: %i[new edit create update destroy]
      end
    end
    resources :users do
      resources :personal_identifications, only: %i[new create edit update]
      member do
        post 'postal_matter_notification' => 'users#postal_matter_notification'
      end
    end
    resources :plans
    resources :user_corps
    resources :corporate_admin_users
    resources :billings, only: %i[index show]
    resources :reservations do
      post :payment, on: :collection
    end
    resources :dropin_reservations, only: %i[index show]
    resources :information
  end
end

app/models/corporation.rb
class Corporation < ApplicationRecord
  before_save :set_corporation_token
  acts_as_paranoid

  has_many :corporation_users, dependent: :destroy
  has_many :users, through: :corporation_users
  has_many :user_corps, class_name: 'UserCorp',
                        through: :corporation_users,
                        source: :user
  has_many :corporate_admin_users, class_name: 'CorporateAdminUser',
                                   through: :corporation_users,
                                   source: :user
  has_many :plans, dependent: :destroy
  has_many :shops, dependent: :destroy
  has_many :user_contracts, dependent: :destroy

  accepts_nested_attributes_for :users

  validates :name, :kana, presence: true, length: { maximum: 255 }
  validates :tel, presence: true, length: { maximum: 255 }
  validates :postal_code, length: { maximum: 255 }
  validates :address, :note, length: { maximum: 255, allow_blank: true }

  enum browsable_range_default: { related_corp_facilities: 0, all_facilities: 1 }

  before_save :generate_token_with_name

  KEYSTATION_ID = 2

  # 企業毎のtoken生成
  def generate_token_with_name
    return if jwt_token.present?
    payload = { name: name, created_at: created_at, partner: true }
    token = JWT.encode payload, Rails.application.secrets.secret_key_base, 'HS256'
    self.jwt_token = token
  end

  def self.sync_from_api
    KeystationService.sync_corporations
  end

  def selectable_keys
    arrs = []
    KeystationService.sync_rooms(ks_corporation_id).each do |arr|
      ks_room_key_ids = FacilityKey.selected(self).pluck(:ks_room_key_id)
      next if ks_room_key_ids.include?(arr[1])
      arrs << arr
    end
    arrs
  end

  def plans_linked_with_user?(user)
    plans.ids.any? { |plan_id| user.contract_plan_ids.include?(plan_id) }
  end

  def selectable_users_for_contract
    selectable_users = users
      .where(user_type: [User.user_types[:personal],
                         User.user_types[:corporate_admin]])
    selectable_users.parent_is_nil.or(users.parent_corporation)
  end

  def set_corporation_token
    return if corporation_token.present?
    self.corporation_token = SecureRandom.hex(16)
  end
end

app/controllers/admin/corporations/users_controller.rb
class Admin::Corporations::UsersController < AdminController
  before_action :set_corporation
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = @corporation.users.order(id: :desc).page(params[:page])
  end

  def new
    @user = User.new
    @user.corporation_users
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "#{User.model_name.human}を作成しました。"
      redirect_to admin_corporation_path(@corporation)
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "#{User.model_name.human}を更新しました。"
      redirect_to admin_corporation_user_path(@corporation, @user)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "#{User.model_name.human}を削除しました。"
    redirect_to admin_corporation_path(params[:corporation_id])
  end

  private

  def set_corporation
    @corporation = Corporation.find(params[:corporation_id])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email, :password, :password_confirmation, :name, :tel, :state, :payway,
      corporation_users_attributes: [:id, :corporation_id]
    )
  end
end

app/controllers/admin/corporations_controller.rb
class Admin::CorporationsController < AdminController
  before_action :set_corporation, only: [:show, :edit, :update, :destroy]

  # GET /admin/corporations
  def index
    @corporations = Corporation.all.order(id: :desc).page(params[:page])
  end

  # GET /admin/corporations/new
  def new
    @corporation = Corporation.new
  end

  # GET /admin/corporations/1/edit
  def edit
  end

  # POST /admin/corporations
  def create
    @corporation = Corporation.new(corporation_params)

    if @corporation.save
      redirect_to [:admin, @corporation], notice: "#{Corporation.model_name.human}を作成しました。"
    else
      render :new
    end
  end

  def show
    @shops = @corporation.shops.order(id: :desc).page(params[:page])
  end

  # PATCH/PUT /admin/corporations/1
  def update
    if @corporation.update(corporation_params)
      redirect_to [:admin, @corporation], notice: "#{Corporation.model_name.human}を更新しました。"
    else
      render :edit
    end
  end

  # DELETE /admin/corporations/1
  def destroy
    @corporation.destroy
    redirect_to admin_corporations_path, notice: "#{Corporation.model_name.human}を削除しました。"
  end

  private

  def set_corporation
    @corporation = Corporation.find(params[:id])
  end

  def corporation_params
    params.require(:corporation).permit(
      :name, :kana, :email, :tel, :fax, :postal_code, :address, :note, :ksc_token, :ks_corporation_id, :verification_required, :browsable_range_default
    )
  end
end

app/controllers/corporation/base.rb
class Corporation::Base < ApplicationController
  class AuthenticateCoroporationError < StandardError; end
  layout 'corporation/layouts/application'
  before_action :authenticate_corporation!

  rescue_from AuthenticateCoroporationError, with: :corporation_not_authorized

  private

  def authenticate_corporation!
    raise AuthenticateCoroporationError unless current_corporation?
  end

  def corporation_not_authorized
    redirect_to root_path, notice: 'アクセスできません'
  end
end

app/controllers/corporation/users_controller.rb
class Corporation::UsersController < ApplicationController
  before_action :set_corporation_from_token

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.corporation_users.new(corporation_id: @corporation.id)
    if @user.save(context: :new_user_registration)
      @user.related_corp_facilities! if @corporation.related_corp_facilities?
      @user.reload
      @user.skip_sms_verification_if_not_required!
      auto_login(@user)
      if @user.sms_verified
        redirect_to root_path, notice: 'ユーザ登録が完了しました'
      else
        redirect_to tel_user_path
      end
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :name,
      :tel,
      :state,
      :payway,
      :user_type,
      :parent_id,
      :advertise_notice_flag,
      :stripe_customer_id,
      :campaign_id,
      :corporation_id,
      :term_of_use,
    )
  end

  def set_corporation_from_token
    @corporation = Corporation.find_by(corporation_token: params[:corporation_token])
    redirect_to root_path, notice: 'URLが不正です' if @corporation.blank?
  end
end

app/views/admin/corporations/_form.html.erb
<%= bootstrap_form_for([:admin, corporation], layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-8") do |f| %>
  <%= f.select :ks_corporation_id, options_for_select(key_corporation_select, selected: f.object.ks_corporation_id), include_blank: true %>
  <%= f.text_field :name %>
  <%= f.text_field :kana %>
  <%= f.text_field :email %>
  <%= f.text_field :tel %>
  <%= f.number_field :postal_code %>
  <%= f.text_field :address %>
  <%= f.text_field :ksc_token %>
  <%= f.select :browsable_range_default, Corporation.browsable_range_defaults_i18n.invert %>
  <%= f.text_field :note %>
  <%= f.select :verification_required, [['必要', true], ['不要', false]] %>
  <%= f.submit class: 'btn btn-primary center-block' %>
<% end %>

app/views/admin/corporations/edit.html.erb
<% breadcrumb :edit_admin_corporation, @corporation %>

<div class="box box-default">
  <div class="box-header with-border">
    <h4 class="box-title"><%= Corporation.model_name.human %>編集</h4>
  </div>
  <div class="box-body">
    <%= render 'form', corporation: @corporation %>
  </div>
</div>

app/views/admin/corporations/index.html.erb
<div class="box box-default">
  <div class="box-header with-border">
    <h4 class="box-title"><%= Corporation.model_name.human %>一覧</h4>
    <div class="box-tools">
      <%= link_to '新規追加', new_admin_corporation_path, class: 'btn btn-info' %>
    </div>
  </div>
  <div class="box-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= Corporation.human_attribute_name(:id) %></th>
          <th><%= Corporation.human_attribute_name(:name) %></th>
          <th><%= Corporation.human_attribute_name(:kana) %></th>
          <th><%= Corporation.human_attribute_name(:tel) %></th>
          <th><%= Corporation.human_attribute_name(:address) %></th>
          <th><%= Corporation.human_attribute_name(:verification_required) %></th>
          <th style="width: 200px;"></th>
        </tr>
      </thead>
      <tbody>
        <% if @corporations.present? %>
          <% @corporations.each do |corporation| %>
            <tr>
              <td><%= corporation.id %></td>
              <td><%= corporation.name %></td>
              <td><%= corporation.kana %></td>
              <td><%= corporation.tel %></td>
              <td><%= corporation.address %></td>
              <td><%= corporation.verification_required ? '必要' : '不要' %></td>
              <td>
                <%= link_to '詳細', admin_corporation_path(corporation), class: 'btn btn-default' %>
                <%= link_to '編集', edit_admin_corporation_path(corporation), class: 'btn btn-primary' %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="20">
              表示する<%= Corporation.model_name.human %>はいません
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @corporations %>
  </div>
</div>

app/views/admin/corporations/new.html.erb
<% breadcrumb :new_admin_corporation %>

<div class="box box-default">
  <div class="box-header with-border">
    <h4 class="box-title"><%= Corporation.model_name.human %>新規登録</h4>
  </div>
  <div class="box-body">
    <%= render 'form', corporation: @corporation %>
  </div>
</div>

app/views/admin/corporations/show.html.erb
<% breadcrumb :admin_corporation, @corporation %>
<div class="box box-default">
  <div class="box-body with-border">
    <div class="box-tools">
      <%= link_to '契約者管理', admin_corporation_user_contracts_path(@corporation), class: 'btn btn-info' %>
      <%= link_to 'プラン管理', admin_corporation_plans_path(@corporation), class: 'btn btn-info' %>
      <%= link_to '施設管理者管理', admin_corporation_corporate_admin_users_path(@corporation), class: 'btn btn-default' %>
    </div>
  </div>
</div>

<div class="box box-default">
  <div class="box-header with-border">
    <h4 class="box-title"><%= Corporation.model_name.human %>詳細</h4>
    <div class="box-tools">
      <%= link_to "戻る", admin_corporations_path, class: 'btn btn-default' %>
      <%= link_to "編集", edit_admin_corporation_path(@corporation), class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="box-body">
    <table class="table table-striped">
      <tr>
        <th><%= Corporation.human_attribute_name(:id) %></th>
        <td><%= @corporation.id %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:ks_corporation_id) %></th>
        <td><%= @corporation.ks_corporation_id %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:name) %></th>
        <td><%= @corporation.name %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:kana) %></th>
        <td><%= @corporation.kana %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:email) %></th>
        <td><%= @corporation.email %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:tel) %></th>
        <td><%= @corporation.tel %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:postal_code) %></th>
        <td><%= @corporation.postal_code %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:jwt_token) %></th>
        <td><%= @corporation.jwt_token %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:ksc_token) %></th>
        <td><%= @corporation.ksc_token %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:browsable_range_default) %></th>
        <td><%= @corporation.browsable_range_default_i18n %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:address) %></th>
        <td><%= @corporation.address %></td>
      </tr>
      <tr>
        <th>ユーザ登録用URL</th>
        <td><%= link_to "#{corporation_new_user_url(corporation_token: @corporation.corporation_token)}",
          corporation_new_user_url(corporation_token: @corporation.corporation_token),
          target: '_blank' %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:note) %></th>
        <td><%= @corporation.note  %></td>
      </tr>
      <tr>
        <th><%= Corporation.human_attribute_name(:verification_required) %></th>
        <td><%= @corporation.verification_required ? '必要' : '不要'  %></td>
      </tr>
    </table>
  </div>
</div>

<div class="box box-default">
  <div class="box-header with-border">
    <h4 class="box-title"><%= Shop.model_name.human %>一覧</h4>
    <div class="box-tools">
      <%= link_to "新規追加", new_admin_corporation_shop_path(@corporation), class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="box-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= Shop.human_attribute_name(:id) %></th>
          <th><%= Shop.human_attribute_name(:name) %></th>
          <th><%= Shop.human_attribute_name(:tel) %></th>
          <th><%= Shop.human_attribute_name(:registerable) %></th>
          <th><%= Shop.human_attribute_name(:disclosure_range) %></th>
          <th style="width: 200px;"></th>
        </tr>
      </thead>
      <tbody>
        <% @shops.each do |shop| %>
          <tr>
            <td><%= shop.id %></td>
            <td><%= shop.name %></td>
            <td><%= shop.tel %></td>
            <td><%= shop.registerable ? '可' : '不可' %></td>
            <td><%= shop.disclosure_range_i18n %></td>
            <td>
              <%= link_to '詳細', admin_corporation_shop_path(@corporation, shop), class: 'btn btn-default' %>
              <%= link_to '編集', edit_admin_corporation_shop_path(@corporation, shop), class: 'btn btn-primary' %>
              <%= link_to '削除', admin_corporation_shop_path(@corporation, shop), method: :delete, data: { confirm: '削除しますか?' }, class: 'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @shops %>
  </div>
</div>