config/routes.rb
Rails.application.routes.draw do

  unless Rails.env.production?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  mount API::Root => '/'

  root 'top#index'
  get '/term_of_use' => 'top#term_of_use'
  get '/privacy_policy' => 'top#privacy_policy'
  get '/special_commercial_code' => 'top#special_commercial_code'

  namespace :admin do
    get '/' => 'dashboards#index'
    get '/sign_in' => 'sessions#new'
    post '/sign_in' => 'sessions#create'
    get '/sign_out' => 'sessions#destroy'
    resources :dashboards, only: [:index]
    resources :admin_users, except: [:show]
    resources :users do
      resources :personal_identifications
      post :proxy_access, on: :member
    end
    resources :user_corps do
      resources :users, controller: 'users' do
        post :proxy_access, on: :member
      end
    end
    resources :information
    resources :corporations do
      resources :corporate_admin_users
      resources :user_contracts
      resources :plans
      resources :facilities, only: [] do
        member do
          get :events
        end
        resources :facility_plans, only: [:new, :create, :destroy]
        resources :facility_dropin_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources, format: 'json'
            get :events, format: 'json'
          end
        end
        resources :facility_temporary_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources
            get :events
          end
        end
        resources :facility_pack_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources
            get :events
          end
        end
      end
      resources :shops, except: [:index] do
        resources :facilities, except: [:index] do
          resources :facility_keys, except: [:index]
        end
      end
    end
    resources :reservations do
      collection do
        get :payment
        get :confirm
      end
    end
    resources :dropin_reservations do
      collection do
        get :payment
        get :confirm
      end
    end
    resources :billings, only: [:index, :show]
  end

  resource :user do
    collection do
      get 'new/:parent_token', to: 'users#new', as: 'new_parent_token'
      get 'tel', to: 'users#tel'
      post 'sms', to: 'users#sms'
      post 'sms_confirm', to: 'users#sms_confirm'
    end
  end
  get '/sign_in' => 'sessions#new'
  post '/sign_in' => 'sessions#create'
  get '/sign_out' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get :reminder
      post :post_reminder
      get 'reset_password/:token', to: 'sessions#reset_password', as: 'reset_password'
      patch 'update_password/:token', to: 'sessions#update_password', as: 'update_password'
    end
  end
  resources :shops, only: [:index, :show] do
    resources :facilities, only: [:new, :create], controller: 'shops/facilities'
  end
  get '/shops/:shop_id/facilities/:id/events' => 'shops/facilities#events'
  resources :facilities, only: [:index, :show]
  resources :reservations, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :price
      get :dropin_spot
      get :spot
      post :confirm
      get :confirm
      post :credit_card
      get :thanks
    end
  end
  resource :personal_identification
  resources :dropin_reservations, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :plan
      get :dropin_spot
      post :confirm
      get :confirm
      post :credit_card
      get :thanks
    end
  end
  resources :plans
  resource :credit_card, only: [:new, :create, :show, :edit, :update]
  resources :invitations, only: [:index, :new, :create]
  resources :information, only: [:index, :show]

  post '/fetch_corporation_ids' => 'corporations#fetch_corporation_ids'

  namespace :corporation do
    get '/:corporation_token/users/new' => 'users#new', as: 'new_user'
    post '/:corporation_token/users' => 'users#create', as: 'user'
  end

  # 法人メニュー
  namespace :corporation_manage do
    root 'dashboards#index'
    resources :user_contracts
    resources :shops, only: %i[new show edit create update destroy] do
      resources :facilities, only: %i[new show edit create update destroy] do
        get :facility_events, on: :member
        resources :facility_keys, only: %i[new show edit create update destroy]
        resources :facility_temporary_plans, only: %i[index new edit create update destroy]
        resources :facility_temporary_plan_prices, only: %i[index]
        resources :facility_dropin_plans, only: %i[index new edit create update destroy]
        resources :facility_dropin_sub_plans, only: %i[index]
        resources :facility_pack_plans, only: %i[new edit create update destroy]
      end
    end
    resources :users do
      resources :personal_identifications, only: %i[new create edit update]
      member do
        post 'postal_matter_notification' => 'users#postal_matter_notification'
      end
    end
    resources :plans
    resources :user_corps
    resources :corporate_admin_users
    resources :billings, only: %i[index show]
    resources :reservations do
      post :payment, on: :collection
    end
    resources :dropin_reservations, only: %i[index show]
    resources :information
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  acts_as_paranoid
  mount_uploader :image, ImageUploader

  belongs_to :corporation
  has_many :facilities, dependent: :destroy
  has_many :information
  has_many :user_contracts
  has_many :shop_plans, dependent: :destroy
  has_many :plans, through: :shop_plans
  accepts_nested_attributes_for :shop_plans

  validates :name, :opening_time, :closing_time, presence: true
  validates :plan_ids, presence: { message: '%{attribute}を選択してください。' }, if: Proc.new { |u| u.for_chose_plan_users? }
  validates :tel,
            length: { maximum: 13 },
            numericality: { only_integer: true, allow_blank: true }
  validate :do_not_over_closing_time

  delegate :name, to: :corporation, prefix: true, allow_nil: true
  delegate :id, to: :corporation, prefix: true, allow_nil: true

  enum disclosure_range: { for_all_users: 0,
                       for_related_users: 1,
                       for_chose_plan_users: 2,
                       closed: 3 }

  # カテゴリ毎の統合用店舗ID
  FLEXIBLE_SHOP_ID = 11

  # 特別対応を行う店舗ID
  WBG_SHOP_ID = 22
  REFCOME_SHOP_ID = 37

  def self.available_shops(user)
    filter_by_disclosure_range(user).to_activerecord_relation.filter_by_browsable_range(user)
  end

  def self.filter_by_disclosure_range(user)
    select { |shop|
      case shop.disclosure_range
      when 'for_all_users'
        true
      when 'for_related_users'
        next if user.blank? || !user.corporations.include?(shop.corporation)
        true
      when 'for_chose_plan_users'
        plan_ids = ShopPlan.where(shop_id: shop).pluck(:plan_id)
        next if user.blank? || !plan_ids.any? { |plan_id| user.contract_plan_ids.include?(plan_id) }
        true
      when 'closed'
        next
      end
    }
  end

  def self.filter_by_browsable_range(user)
    user.present? && user.related_corp_facilities? ? where(corporation_id: user.corporation_ids) : all
  end

  def self.belongs_to_corporation(c_id)
    Corporation.find(c_id).shops
  end

  # RemoteLockを使用する店舗のID一覧(名前にRemoteLockって含まれる店舗一覧)
  def self.with_remote_lock_shops
    Shop.where('name LIKE ?', '%RemoteLock%')
  end

  def do_not_over_closing_time
    return if opening_time.nil? || closing_time.nil?
    return if opening_time < closing_time
    errors.add(:opening_time, :do_not_over_closing_time)
  end

  def assign_date_for_opening(y, m, d)
    opening_time.change(year: y, month: m, day: d)
  end

  def assign_date_for_closing(y, m, d)
    closing_time.change(year: y, month: m, day: d)
  end

  # 日付範囲が店舗の営業時間外かどうか
  def out_of_business_time?(from, to)
    return not_around_the_clock if from.strftime('%Y/%m/%d') != to.strftime('%Y/%m/%d')
    from < assign_date_for_opening(from.year, from.month, from.day) ||
      to > assign_date_for_closing(from.year, from.month, from.day)
  end

  # 24時間営業ではない
  def not_around_the_clock
    closing_time != opening_time + 1.days - 1.minutes
  end

  # フレキシブル利用用の店舗かどうか
  def for_flexible?
    id == Shop::FLEXIBLE_SHOP_ID
  end

  def set_geocode
    uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+self.address.gsub(" ", "")+"&key=#{Settings.google_key}")
    res = HTTP.get(uri).to_s
    response = JSON.parse(res)
    if response['results'].present?
      self.lat = response["results"][0]["geometry"]["location"]["lat"]
      self.lon = response["results"][0]["geometry"]["location"]["lng"]
    end
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < AdminController
  before_action :set_corporation
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def new
    @shop = Shop.new
  end

  def create
    @shop = @corporation.shops.new(set_params)
    @shop.set_geocode
    if @shop.save
      redirect_to [:admin, @corporation, @shop], notice: "#{Shop.model_name.human}を作成しました。"
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    @shop.assign_attributes(set_params)
    @shop.set_geocode
    if @shop.save
      redirect_to [:admin, @corporation, @shop], notice: "#{Shop.model_name.human}を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to admin_corporation_path(@corporation)
  end

  private

  def set_params
    if shop_params[:disclosure_range] != 'for_chose_plan_users'
      shop_params_to_variable = shop_params
      shop_params_to_variable[:plan_ids].clear
      shop_params_to_variable
    else
      shop_params
    end
  end

  def set_corporation
    @corporation = Corporation.find(params[:corporation_id])
  end

  def set_shop
    @shop = @corporation.shops.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(
      :name, :postal_code, :address, :lat, :lon, :tel, :opening_time, :closing_time, :image, :calendar_url, :registerable, :disclosure_range, {plan_ids: []}
    )
  end
end

app/controllers/corporation_manage/shops_controller.rb
class CorporationManage::ShopsController < CorporationManage::Base
  before_action :set_shop, only: %i[show edit update destroy]

  def new
    @shop = current_corporation.shops.build
  end

  def create
    @shop = current_corporation.shops.build(set_params)
    @shop.set_geocode
    if @shop.save
      redirect_to corporation_manage_shop_path(@shop), notice: "#{Shop.model_name.human}を作成しました。"
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    @shop.assign_attributes(set_params)
    @shop.set_geocode
    if @shop.save
      redirect_to corporation_manage_shop_path(@shop), notice: "#{Shop.model_name.human}を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy!
    redirect_to corporation_manage_root_path, notice: "#{Shop.model_name.human}を削除しました。"
  end

  private

  def set_params
    if shop_params[:disclosure_range] != 'for_chose_plan_users'
      shop_params_to_variable = shop_params
      shop_params_to_variable[:plan_ids].clear
      shop_params_to_variable
    else
      shop_params
    end
  end

  def set_shop
    @shop = current_corporation.shops.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(
      :name,
      :postal_code,
      :address,
      :lat,
      :lon,
      :tel,
      :opening_time,
      :closing_time,
      :image,
      :calendar_url,
      :registerable,
      :disclosure_range,
      {plan_ids: []}
    )
  end
end

app/controllers/shops/facilities_controller.rb
class Shops::FacilitiesController <  ApplicationController
  include SearchParams

  before_action :require_login, only: [:new, :create]
  before_action :require_sms_verification, only: [:new, :create]
  before_action :set_user
  before_action :set_facility
  before_action :set_shop

  def new
    redirect_to root_path, alert: '現在掲載停止中の施設です。' if !@facility.published
    @condition = params[:spot] ||= {}
    set_choosable_pack_plans
  end

  def create
    @condition = params[:spot] ||= {}
    return render :new if @condition.blank?
    set_choosable_pack_plans
    set_selected_pack_plan_id(@condition)
    return render :new unless valid_search_params?(@condition) #@checkinと@checkoutもset
    session[:spot] = @condition
    redirect_to confirm_reservations_url(page: :shop)
  end

  def events
    @start = params[:start]
    @end = params[:end]
  end

  private

  def set_user
    @user = current_user_corp.present? ? current_user_corp : current_user if logged_in?
  end

  def set_facility
    @facility = Facility.find(params[:id])
  end

  def set_choosable_pack_plans
    @choosable_pack_plans = @facility.choosable_pack_plans(@user).flatten.to_activerecord_relation.order(:unit_time)
  end

  def set_selected_pack_plan_id(condition)
    @selected_pack_plan_id = @choosable_pack_plans.find_by(id: condition[:pack_plan_id]).id if condition[:pack_plan_id].present?
  end

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_user
  before_action :set_shop, :set_facilities, :set_dropin_facilities, :set_accommodation_facilities, only: [:show]

  def index
    @q = Shop.available_shops(@user).ransack(params[:q])
    @shops = @q.result.order(id: :desc).page(params[:page])
  end

  def show
    if @shop.for_flexible?
      current_user_corporation_shops = Shop.where(corporation_id: current_user.corporations.pluck(:id))
      @flexible_facilities = Facility
                            .ks_flexible
                            .where(shop_id: current_user_corporation_shops.map{|s| s.id})
                            .where(published: true)
                            .order(id: :desc)
                            .page(params[:page])
    else
      @facilities = @facilities.order(id: :asc).page(params[:page])
      @dropin_facilities = @dropin_facilities.order(id: :asc).page(params[:page])
      @accommodation_facilities = @accommodation_facilities.order(id: :asc).page(params[:page])
    end
  end

  private

  def set_facilities
    @facilities = current_user.present? ? current_user.conference_room_facilities(@shop) : @shop.facilities.conference_room_facilities
  end

  def set_dropin_facilities
    @dropin_facilities = current_user.present? ? current_user.dropin_facilities(@shop) : @shop.facilities.dropin_facilities
  end

  def set_accommodation_facilities
    @accommodation_facilities = current_user.present? ? current_user.accommodation_facilities(@shop) : @shop.facilities.accommodation_facilities
  end

  def set_user
    @user = current_user_corp.present? ? current_user_corp : current_user if logged_in?
  end

  def set_shop
    @shop = Shop.available_shops(@user).find(params[:id])
  end
end

app/helpers/shop_helper.rb
module ShopHelper

  def selectable_shops
    Shop.where(registerable: true).map{ |s| [s.name, s.corporation_id] }
  end

  def need_liferee_link?
    hundled_on_liferee_shops_ids = [32, 33]
    @shop.id.in?(hundled_on_liferee_shops_ids)
  end
end

app/views/shops/_for_flexible.html.erb
<div class="mg-single-room">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <%= image_tag @shop.image_url(:main), class: 'img-responsive' %>
      </div>
      <div class="col-md-5 mg-room-fecilities">
        <h2 class="mg-sec-left-title"><%= @shop.name %></h2>
        <div class="row">
          <div class="col-xs-12">
            <div class="row mg-room-fecilities">
              <div class="col-sm-12">
                <ul class='ul-newline'>
                  <li>
                    <%= "電話: #{tel_fmt(@shop.tel)}" %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="mg-single-room-txt">
          <h3 class="mg-shop-facility-title">利用可能施設一覧</h3>
          <% if @flexible_facilities.present? %>
            <% @flexible_facilities.each do |facility| %>
              <div class="mg-available-rooms">
                <div class="row">
                  <div class="col-sm-4">
                    <%= image_tag facility.image.main.url, class: 'img-responsive' %>
                  </div>
                  <div class="col-sm-8">
                    <h3 class="mg-avl-room-title">
                      <%= link_to new_reservation_path(facility_id: facility.id) do %>
                        <%= facility.name %>
                      <% end %>
                    </h3>
                    <div class='row mg-room-fecilities'>
                      <div class='col-sm-12'>
                        <ul>
                          <li>
                            <i class="fa fa-home"></i>
                            <span class="mg-desc-text"><%= facility.address %></span>
                          </li>
                        </ul>
                      </div>
                    </div>

                    <div>
                      <div class='col-sm-6'>
                        <% if facility.lat? && facility.lon? %>
                          <div class="google-map" style="height: 200px;" data-lat="<%= facility.lat %>" data-lon="<%= facility.lon %>"></div>
                        <% end %>
                      </div>
                      <div class='col-sm-6 text-right' style='height: 200px; position: relative;'>
                        <%= link_to new_shop_facility_path(@shop, id: facility.id), class: 'btn btn-main', style: 'position: absolute; bottom: 0; right:30px;' do %>
                          利用予約<i class="fa fa-angle-double-right"></i>
                        <% end %>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            <% end %>
          <% else %>
            <div class="mg-available-rooms">
              <div class="row">
                <div class="col-md-12 text-center">
                  現在利用可能な施設はありません。
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <br/>
  </div>
</div>

app/views/shops/_for_shop.html.erb
<div class="mg-single-room">
  <div class="container">
    <div class="row mb-20">
      <div class="col-md-7">
        <%= image_tag @shop.image_url(:main), class: 'img-responsive' %>
      </div>
      <div class="col-md-5 mg-room-fecilities">
        <h2 class="mg-sec-left-title"><%= @shop.name %></h2>
        <div class="row">
          <div class="col-xs-12 shop_info">
            <p> <%= "〒#{@shop.postal_code} #{@shop.address}" %></p>
            <p><%= "電話: #{tel_fmt(@shop.tel)}" %></p>
            <p><%= "営業時間: #{time_fmt(@shop.opening_time)} - #{time_fmt(@shop.closing_time)}" %></p>
            <div class="col-md-12 shop_map">
              <% if @shop.lat? && @shop.lon? %>
                <div class="google-map ml0" style="height: 239px;" data-lat="<%= @shop.lat %>" data-lon="<%= @shop.lon %>" data-name="<%= @shop.name %>"  data-address="<%= @shop.address %>"></div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="shop_link">
      <%= link_to "時間指定予約", {anchor: "shop_show_conference_rooms"}, class: "shop_link_button fas fa-chevron-circle-down lower_by_header" %>
      <%= link_to "1DAY利用(ドロップイン)", {anchor: "shop_show_dropins"}, class: "shop_link_button fas fa-chevron-circle-down lower_by_header" %>
      <% if need_liferee_link? %><%# 三浦と一宮のみリンク表示 %>
        <%= link_to "宿泊利用はこちらよりお問い合わせ下さい。", "https://www.life-ree.com/2348727850201043200412501124571254012512.html", class: "shop_link_button fas fa-external-link-alt", target: "_blank", rel:"noopener" %>
      <% else %>
      <%= link_to "宿泊利用", {anchor: "shop_show_accommodations"}, class: "shop_link_button fas fa-chevron-circle-down lower_by_header" %>
      <% end %>
    </div>
    <div class="row" id="shop_show_conference_rooms">
      <div class="col-md-12">
        <div class="mg-single-room-txt">
          <h3 class="mg-shop-facility-title">時間指定予約</h3>
          <div class="mg-available-rooms">
            <% if @facilities.present? %>
              <% @facilities.each_with_index do |facility, i| %>
                  <div class="row mb20 calendar_toggle_parent">
                    <div class="col-sm-4">
                      <%= image_tag facility.image.main.url, class: 'img-responsive' %>
                    </div>
                    <div class="col-sm-8">
                      <h3 class="mg-avl-room-title">
                        <%= link_to new_shop_facility_path(@shop, id: facility.id) do %>
                          <%= facility.name %>
                        <% end %>
                        <span>&yen;<%= facility.min_hourly_price(@user) %> / h 〜</span>
                      </h3>
                      <div class='row mg-room-fecilities'>
                        <div class='col-sm-12'>
                          <ul>
                            <li>
                              <i class="fa fa-user"></i>
                              <span class="mg-desc-text"><%= facility.max_num %>人まで</span>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <%# jQueryでクラス名の先頭という条件を使っているので「conference_room_calendar」は先頭固定 %>
                    <a class="conference_room_calendar btn far fa-calendar-alt calendar_toggle" id="<%= i %>"><span> 空き状況カレンダーを開く</span><span> 空き状況カレンダーを閉じる</span></a>
                  </div>
                  <div class="mb20 calendar_wrapper" id=<%= "conference_room_calendar#{i}_wrapper" %>>
                    <div class="col-md-12">
                      <span class='rect-shape rect-today'></span><span class='rect-text'>本日</span>
                      <span class='rect-shape rect-available'></span><span class='rect-text'>予約可</span>
                      <span class='rect-shape rect-full-booking'></span><span class='rect-text'>予約不可</span>
                      <span class='rect-shape rect-out-of-business-hours'></span><span class='rect-text'>営業時間外</span>
                    </div>
                    <div id=<%= "conference_room_calendar#{i}" %> class="user_reservation_calendar"
                      data-shop=<%="#{facility.shop.id}"%>
                      data-facility=<%="#{facility.id}"%>>
                    </div>
                  </div>
              <% end %>
            <% else %>
              <div class="row">
                <div class="col-md-12 text-center">
                  現在利用可能な施設はありません。
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="row" id="shop_show_dropins">
      <div class="col-md-12">
        <h3 class="mg-shop-facility-title">1DAY利用(ドロップイン)</h3>
          <div class="mg-available-rooms">
            <% if @dropin_facilities.present? %>
              <% @dropin_facilities.each do |facility| %>
                  <div class="row">
                    <div class="col-sm-4">
                      <%= image_tag facility.image.main.url, class: 'img-responsive' %>
                    </div>
                    <div class="col-sm-8">
                      <h3 class="mg-avl-room-title">
                        <%= link_to new_dropin_reservation_path(dropin_spot: { facility_id: facility.id, checkin: "" }) do %>
                          <%= facility.name %>
                        <% end %>
                      </h3>
                    </div>
                  </div>
              <% end %>
            <% else %>
              <div class="col-md-12 text-center">
                現在利用可能な施設はありません。
              </div>
            <% end %>
          </div>
        </h3>
      </div>
    </div>
    <% unless need_liferee_link? %><%# 三浦と一宮は非表示 %>
      <div class="row" id="shop_show_accommodations">
        <div class="col-md-12">
          <h3 class="mg-shop-facility-title">宿泊利用</h3>
            <div class="mg-available-rooms">
              <% if @accommodation_facilities.present? %>
                <% @accommodation_facilities.each_with_index do |facility, i| %>
                  <div class="row mb20 calendar_toggle_parent">
                    <div class="col-sm-4">
                      <%= image_tag facility.image.main.url, class: 'img-responsive' %>
                    </div>
                    <div class="col-sm-8">
                      <h3 class="mg-avl-room-title">
                        <%= link_to new_reservation_path(facility_id: facility.id) do %>
                          <%= facility.name %>
                        <% end %>
                      </h3>
                      <div class='row mg-room-fecilities'>
                        <div class='col-sm-12'>
                          <ul>
                            <li>
                              <i class="fa fa-user"></i>
                              <span class="mg-desc-text"><%= facility.max_num %>人まで</span>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <%# jQueryでクラス名の先頭という条件を使っているので「accommodation_calendar」は先頭固定 %>
                    <a class="accommodation_calendar btn far fa-calendar-alt calendar_toggle" id="<%= i %>"><span> 空き状況カレンダーを開く</span><span> 空き状況カレンダーを閉じる</span></a>
                  </div>
                  <div class="mb20 calendar_wrapper" id=<%= "accommodation_calendar#{i}_wrapper" %>>
                    <div class="col-md-12">
                      <span class='rect-shape rect-today'></span><span class='rect-text'>本日</span>
                      <span class='rect-shape rect-available'></span><span class='rect-text'>予約可</span>
                      <span class='rect-shape rect-full-booking'></span><span class='rect-text'>予約不可</span>
                      <span class='rect-shape rect-out-of-business-hours'></span><span class='rect-text'>営業時間外</span>
                    </div>
                    <div id=<%= "accommodation_calendar#{i}" %> class="user_reservation_calendar"
                      data-shop=<%="#{facility.shop.id}"%>
                      data-facility=<%="#{facility.id}"%>>
                    </div>
                  </div>
                <% end %>
              <% else %>
                <div class="col-md-12 text-center">
                  現在利用可能な施設はありません。
                </div>
              <% end %>
            </div>
          </h3>
        </div>
      </div>
    <% end %>
    <br/>
  </div>
</div>

app/views/shops/index.html.erb
<% content_for :middle_title do %>
  <h2>店舗情報</h2>
<% end %>
<div class="mg-page mg-available-rooms">
  <div class="container">
    <div class="row">
      <div class="search_form mb20 col-md-12">
        <%= search_form_for @q, url: shops_path, class: "form-inline" do |f| %>
          <%= f.search_field :name_or_address_cont, class: 'form-control mb0', placeholder: '店舗名・住所' %>
          <%= f.submit "検索", class: "btn btn-info w40 mr10" %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <% @shops.each do |shop| %>
          <div class="mg-avl-room">
            <div class="row">
              <div class="col-sm-4">
                <% if shop.image? %>
                  <%= link_to shop_path(shop) do %>
                    <%= image_tag shop.image_url(:main), class: 'img-responsive' %>
                  <% end %>
                <% else %>
                  <%= link_to shop_path(shop) do %>
                    <%= image_tag 'noimage.png', class: 'img-responsive' %>
                  <% end %>
                <% end %>
              </div>
              <div class="col-sm-4">
                <h4 class="mg-avl-room-title">
                  <%= link_to shop_path(shop) do %>
                    <%= shop.name %>
                  <% end %>
                </h4>
                <p>
                <%= "〒#{shop.postal_code} #{shop.address}" %>
                </p>
                <div>
                  <%= "電話: #{tel_fmt(shop.tel)}" %>
                </div>
                <div>
                  <%= "営業時間: #{time_fmt(shop.opening_time)} - #{time_fmt(shop.closing_time)}" %>
                </div>
              </div>
              <div class="col-sm-4">
                <% if shop.lat? && shop.lon? %>
                  <div class="google-map" data-lat="<%= shop.lat %>" data-lon="<%= shop.lon %>" data-name="<%= shop.name %>"  data-address="<%= shop.address %>"></div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate @shops %>
      </div>
    </div>
  </div>
</div>

app/views/shops/show.html.erb
<% content_for :middle_title do %>
  <h2><%= "#{@shop.name}" %></h2>
<% end %>
<% if @shop.for_flexible? %>
  <%= render 'for_flexible' %>
<% else %>
  <%= render 'for_shop' %>
<% end %>