config/routes.rb
Rails.application.routes.draw do

  unless Rails.env.production?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  mount API::Root => '/'

  root 'top#index'
  get '/term_of_use' => 'top#term_of_use'
  get '/privacy_policy' => 'top#privacy_policy'
  get '/special_commercial_code' => 'top#special_commercial_code'

  namespace :admin do
    get '/' => 'dashboards#index'
    get '/sign_in' => 'sessions#new'
    post '/sign_in' => 'sessions#create'
    get '/sign_out' => 'sessions#destroy'
    resources :dashboards, only: [:index]
    resources :admin_users, except: [:show]
    resources :users do
      resources :personal_identifications
      post :proxy_access, on: :member
    end
    resources :user_corps do
      resources :users, controller: 'users' do
        post :proxy_access, on: :member
      end
    end
    resources :information
    resources :corporations do
      resources :corporate_admin_users
      resources :user_contracts
      resources :plans
      resources :facilities, only: [] do
        member do
          get :events
        end
        resources :facility_plans, only: [:new, :create, :destroy]
        resources :facility_dropin_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources, format: 'json'
            get :events, format: 'json'
          end
        end
        resources :facility_temporary_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources
            get :events
          end
        end
        resources :facility_pack_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources
            get :events
          end
        end
      end
      resources :shops, except: [:index] do
        resources :facilities, except: [:index] do
          resources :facility_keys, except: [:index]
        end
      end
    end
    resources :reservations do
      collection do
        get :payment
        get :confirm
      end
    end
    resources :dropin_reservations do
      collection do
        get :payment
        get :confirm
      end
    end
    resources :billings, only: [:index, :show]
  end

  resource :user do
    collection do
      get 'new/:parent_token', to: 'users#new', as: 'new_parent_token'
      get 'tel', to: 'users#tel'
      post 'sms', to: 'users#sms'
      post 'sms_confirm', to: 'users#sms_confirm'
    end
  end
  get '/sign_in' => 'sessions#new'
  post '/sign_in' => 'sessions#create'
  get '/sign_out' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get :reminder
      post :post_reminder
      get 'reset_password/:token', to: 'sessions#reset_password', as: 'reset_password'
      patch 'update_password/:token', to: 'sessions#update_password', as: 'update_password'
    end
  end
  resources :shops, only: [:index, :show] do
    resources :facilities, only: [:new, :create], controller: 'shops/facilities'
  end
  get '/shops/:shop_id/facilities/:id/events' => 'shops/facilities#events'
  resources :facilities, only: [:index, :show]
  resources :reservations, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :price
      get :dropin_spot
      get :spot
      post :confirm
      get :confirm
      post :credit_card
      get :thanks
    end
  end
  resource :personal_identification
  resources :dropin_reservations, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :plan
      get :dropin_spot
      post :confirm
      get :confirm
      post :credit_card
      get :thanks
    end
  end
  resources :plans
  resource :credit_card, only: [:new, :create, :show, :edit, :update]
  resources :invitations, only: [:index, :new, :create]
  resources :information, only: [:index, :show]

  post '/fetch_corporation_ids' => 'corporations#fetch_corporation_ids'

  namespace :corporation do
    get '/:corporation_token/users/new' => 'users#new', as: 'new_user'
    post '/:corporation_token/users' => 'users#create', as: 'user'
  end

  # 法人メニュー
  namespace :corporation_manage do
    root 'dashboards#index'
    resources :user_contracts
    resources :shops, only: %i[new show edit create update destroy] do
      resources :facilities, only: %i[new show edit create update destroy] do
        get :facility_events, on: :member
        resources :facility_keys, only: %i[new show edit create update destroy]
        resources :facility_temporary_plans, only: %i[index new edit create update destroy]
        resources :facility_temporary_plan_prices, only: %i[index]
        resources :facility_dropin_plans, only: %i[index new edit create update destroy]
        resources :facility_dropin_sub_plans, only: %i[index]
        resources :facility_pack_plans, only: %i[new edit create update destroy]
      end
    end
    resources :users do
      resources :personal_identifications, only: %i[new create edit update]
      member do
        post 'postal_matter_notification' => 'users#postal_matter_notification'
      end
    end
    resources :plans
    resources :user_corps
    resources :corporate_admin_users
    resources :billings, only: %i[index show]
    resources :reservations do
      post :payment, on: :collection
    end
    resources :dropin_reservations, only: %i[index show]
    resources :information
  end
end

app/models/user_contract.rb
class UserContract < ApplicationRecord
  acts_as_paranoid
  belongs_to :corporation
  belongs_to :shop, optional: true
  belongs_to :user
  belongs_to :plan, optional: true

  delegate :name, to: :user, prefix: true, allow_nil: true
  delegate :name, to: :shop, prefix: true, allow_nil: true
  delegate :name, to: :plan, prefix: true, allow_nil: true

  enum state: { applying: 0, under_contract: 1, finished: 9 }

  validates :user_id, :started_on, :state, presence: true
  validate :contract_period

  def contract_period
    return if finished_on.blank?
    errors.add(:started_on, '契約開始日は契約終了日より早めにしてください') if started_on > finished_on
  end
end

app/controllers/admin/user_contracts_controller.rb
class Admin::UserContractsController < AdminController
  before_action :set_corporation
  before_action :set_user_contract, only: [:show, :edit, :update, :destroy]

  def index
    @q = @corporation.user_contracts.ransack(params[:q])
    @user_contracts = @q.result.includes(:user)
    @user_contracts = @user_contracts.order(id: :desc).page(params[:page])
  end

  def new
    @user_contract = @corporation.user_contracts.new
  end

  def create
    @user_contract = @corporation.user_contracts.new(user_contract_params)
    if @user_contract.save
      redirect_to [:admin, @corporation, @user_contract], notice: "#{UserContract.model_name.human}を作成しました。"
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @user_contract.update(user_contract_params)
      redirect_to [:admin, @corporation, @user_contract], notice: "#{UserContract.model_name.human}を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user_contract.destroy
    redirect_to admin_corporation_path(@corporation)
  end

  private

  def set_corporation
    @corporation = Corporation.find(params[:corporation_id])
  end

  def set_user_contract
    @user_contract = @corporation.user_contracts.find(params[:id])
  end

  def user_contract_params
    params.require(:user_contract).permit(
      :shop_id, :user_id, :plan_id, :started_on, :finished_on, :state
    )
  end
end

app/controllers/corporation_manage/user_contracts_controller.rb
class CorporationManage::UserContractsController < CorporationManage::Base
  before_action :set_user_contract, only: %i[show edit update destroy]

  def index
    @user_contracts = current_corporation.user_contracts.order(id: :desc).page(params[:page])
  end

  def new
    @user_contract = current_corporation.user_contracts.build
  end

  def create
    @user_contract = current_corporation.user_contracts.build(user_contract_params)
    if @user_contract.save
      redirect_to corporation_manage_user_contract_path(@user_contract), notice: "#{UserContract.model_name.human}を作成しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @user_contract.update(user_contract_params)
      redirect_to corporation_manage_user_contract_path(@user_contract), notice: "#{UserContract.model_name.human}を更新しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user_contract.destroy!
    redirect_to corporation_manage_user_contracts_path, notice: "#{UserContract.model_name.human}を削除しました。"
  end

  private

  def set_user_contract
    @user_contract = current_corporation.user_contracts.find(params[:id])
  end

  def user_contract_params
    params.require(:user_contract).permit(
      :shop_id,
      :user_id,
      :plan_id,
      :started_on,
      :finished_on,
      :state
    )
  end
end

app/controllers/user_contracts_controller.rb
class UserContractsController < ApplicationController
  before_action :set_shop, :set_plan
  before_action :set_user_contract, only: [:show]

  def new; end

  def create
    @user_contract = current_user.user_contracts.new(user_contract_params)
    @user_contract.corporation_id = @user_contract.shop.corporation_id
    @user_contract.started_on = Time.zone.now
    if @user_contract.save
      @user_contract.corporation.users.each do |cu|
        NotificationMailer.new_user_contract(cu, @user_contract).deliver_now
      end
      redirect_to shop_plan_user_contract_path(@shop, @plan, @user_contract), notice: "#{UserContract.model_name.human}を作成しました。"
    else
      render :new
    end
  end

  def show; end

  def credit_card
    @user_contract = current_user.user_contracts.build
  end

  private

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end

  def set_plan
    @plan = Plan.find(params[:plan_id])
  end

  def set_user_contract
    @user_contract = current_user.user_contracts.find(params[:id])
  end

  def user_contract_params
    params.require(:user_contract).permit(
      :plan_id, :shop_id
    )
  end
end

app/views/user_contracts/_plan.erb
<aside class="mg-widget mt50" id="mg-room-cart">
<h2 class="mg-widget-title">プラン情報</h2>
  <div class="mg-widget-cart">
    <div class="mg-widget-cart-row">
      <strong><%= Plan.human_attribute_name(:name) %></strong>
      <span><%= plan.name %></span>
    </div>
    <div class="mg-widget-cart-row">
      <strong><%= UserContract.human_attribute_name(:started_on) %></strong>
      <span><%= date_ja(Time.zone.now) %></span>
    </div>
    <div class="mg-widget-cart-row">
      <strong><%= Plan.human_attribute_name(:description) %></strong>
      <span><%= plan.description %></span>
    </div>
    <div class="mg-cart-total">
      <strong><%= Plan.human_attribute_name(:price) %>:</strong>
      <span><%= delimiter_price(plan.price) %></span>
    </div>
  </div>
</aside>

app/views/user_contracts/_shop.html.erb
<% if shop.image? %>
  <%= link_to shop_path(shop) do %>
    <%= image_tag shop.image_url(:main), class: 'img-responsive' %>
  <% end %>
  <% else %>
    <%= link_to shop_path(shop) do %>
      <%= image_tag 'noimage.png', class: 'img-responsive' %>
    <% end %>
<% end %>
<table class="table table-striped">
  <tr>
    <th><%= Shop.human_attribute_name(:name) %></th>
    <td><%= shop.name %></td>
  </tr>
  <tr>
    <th><%= Shop.human_attribute_name(:tel) %></th>
    <td><%= shop.tel %></td>
  </tr>
  <tr>
    <th><%= Shop.human_attribute_name(:address) %></th>
    <td><%= shop.address %></td>
  </tr>
  <tr>
    <th><%= Shop.human_attribute_name(:opening_time) %></th>
    <td><%= time_fmt(shop.opening_time) %></td>
  </tr>
  <tr>
    <th><%= Shop.human_attribute_name(:closing_time) %></th>
    <td><%= time_fmt(shop.closing_time) %></td>
  </tr>
</table>

app/views/user_contracts/credit_card.html.erb
<% content_for :middle_title do %>
  <h2>申し込み</h2>
<% end %>
<div class="mg-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="mg-booking-form">
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade active in">
              <div class='row'>
                <div class="col-md-8">
                  <div class="mg-book-form-personal">
                    <h2 class="mg-sec-left-title">クレジットカード情報</h2>
                    <table class="table table-striped">
                      <tr>
                        <th><%= CreditCard.human_attribute_name(:holder_name) %>
                        <td><%= current_user.credit_card.holder_name %></td>
                      </tr>
                      <tr>
                        <th><%= CreditCard.human_attribute_name(:number) %></th>
                        <td><%= current_user.credit_card.full_card_no %></td>
                      </tr>
                    </table>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="mg-cart-container">
                    <%= render 'plan', plan: @plan %>
                  </div>
                </div>
                <div class="col-md-6">
                  <%= bootstrap_form_for [@shop, @plan, @user_contract] do |f| %>
                    <%= f.hidden_field :plan_id, value: @plan.id %>
                    <%= f.hidden_field :shop_id, value: @shop.id %>
                    <%= f.submit '申し込み', class: 'btn btn-dark-main pull-right' %>
                  <% end %>
                  <%= link_to '戻る', new_shop_plan_user_contract_path(@shop.id, @plan.id), class: 'btn btn-default pull-left' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user_contracts/new.html.erb
<% content_for :middle_title do %>
  <h2>申し込み</h2>
<% end %>
<div class="mg-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="mg-booking-form">
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade active in">
              <div class='row'>
                <div class="col-md-8">
                  <div class="mg-book-form-personal">
                    <h2 class="mg-sec-left-title">スペース情報</h2>
                    <%= render 'shop', shop: @shop %>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="mg-cart-container">
                    <%= render 'plan', plan: @plan %>
                  </div>
                </div>
                <div class="col-md-8">
                  <%= link_to '次へ', current_user.credit_card.present? ? shop_plan_user_contracts_credit_card_path(@shop.id, @plan.id) : new_credit_card_path(shop_id: @shop.id, plan_id: @plan.id), class: 'btn btn-dark-main pull-right' %>
                  <%= link_to '戻る', shop_path(@shop), class: 'btn btn-default pull-left' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user_contracts/show.html.erb
<% content_for :middle_title do %>
  <h2>申し込み</h2>
<% end %>
<div class="mg-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="mg-booking-form">
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade active in">
              <div class="alert alert-success alert-dismissible clearfix">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="mg-alert-icon"><i class="fa fa-check"></i></div>
                <h3 class="mg-alert-payment">この度は、お申込み頂き、誠にありがとうございます。</h3>
              </div>
              <div class="mg-cart-container mg-paid">
                <aside class="mg-widget mt50" id="mg-room-cart">
                  <h2 class="mg-widget-title">申し込みの詳細</h2>
                  <div class="mg-widget-cart">
                    <div class="row">
                      <div class="col-md-6">
                        <div class="mg-cart-room">
                          <%= image_tag @user_contract.shop.image_url(:main), class: 'img-responsive' %>
                          <h3><%= @user_contract.plan.name %></h3>
                          <p>
                            <%= @user_contract.plan.description %>
                          </p>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <h3 class="mg-payment-id"><%= @user_contract.shop.name %></h3>
                        <div class="mg-widget-cart-row">
                          <strong><%= UserContract.human_attribute_name(:started_on) %></strong>
                          <span><%= @user_contract.started_on %></span>
                        </div>
                        <div class="mg-widget-cart-row">
                          <strong><%= Shop.human_attribute_name(:opening_time) %></strong>
                          <span><%= time_fmt(@user_contract.shop.opening_time) %></span>
                        </div>
                        <div class="mg-widget-cart-row">
                          <strong><%= Shop.human_attribute_name(:closing_time) %></strong>
                          <span><%= time_fmt(@user_contract.shop.closing_time) %></span>
                        </div>
                        <div class="mg-widget-cart-row">
                          <strong><%= Shop.human_attribute_name(:tel) %></strong>
                          <span><%= tel_fmt(@user_contract.shop.tel) %></span>
                        </div>
                        <div class="mg-cart-address">
                          <strong><%= Shop.human_attribute_name(:address) %></strong>
                          <address>
                            <strong><%= @user_contract.shop.postal_code %></strong><br>
                              <%= @user_contract.shop.address %>
                          </address>
                        </div>
                        <div class="mg-cart-total">
                          <strong><%= Plan.human_attribute_name(:price) %>:</strong>
                          <span><%= delimiter_price(@user_contract.plan.price) %></span>
                        </div>
                      </div>
                    </div>
                  </div>
                </aside>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>