config/routes.rb
Rails.application.routes.draw do

  unless Rails.env.production?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  mount API::Root => '/'

  root 'top#index'
  get '/term_of_use' => 'top#term_of_use'
  get '/privacy_policy' => 'top#privacy_policy'
  get '/special_commercial_code' => 'top#special_commercial_code'

  namespace :admin do
    get '/' => 'dashboards#index'
    get '/sign_in' => 'sessions#new'
    post '/sign_in' => 'sessions#create'
    get '/sign_out' => 'sessions#destroy'
    resources :dashboards, only: [:index]
    resources :admin_users, except: [:show]
    resources :users do
      resources :personal_identifications
      post :proxy_access, on: :member
    end
    resources :user_corps do
      resources :users, controller: 'users' do
        post :proxy_access, on: :member
      end
    end
    resources :information
    resources :corporations do
      resources :corporate_admin_users
      resources :user_contracts
      resources :plans
      resources :facilities, only: [] do
        member do
          get :events
        end
        resources :facility_plans, only: [:new, :create, :destroy]
        resources :facility_dropin_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources, format: 'json'
            get :events, format: 'json'
          end
        end
        resources :facility_temporary_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources
            get :events
          end
        end
        resources :facility_pack_plans, only: [:new, :edit, :create, :update, :destroy] do
          collection do
            get :resources
            get :events
          end
        end
      end
      resources :shops, except: [:index] do
        resources :facilities, except: [:index] do
          resources :facility_keys, except: [:index]
        end
      end
    end
    resources :reservations do
      collection do
        get :payment
        get :confirm
      end
    end
    resources :dropin_reservations do
      collection do
        get :payment
        get :confirm
      end
    end
    resources :billings, only: [:index, :show]
  end

  resource :user do
    collection do
      get 'new/:parent_token', to: 'users#new', as: 'new_parent_token'
      get 'tel', to: 'users#tel'
      post 'sms', to: 'users#sms'
      post 'sms_confirm', to: 'users#sms_confirm'
    end
  end
  get '/sign_in' => 'sessions#new'
  post '/sign_in' => 'sessions#create'
  get '/sign_out' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get :reminder
      post :post_reminder
      get 'reset_password/:token', to: 'sessions#reset_password', as: 'reset_password'
      patch 'update_password/:token', to: 'sessions#update_password', as: 'update_password'
    end
  end
  resources :shops, only: [:index, :show] do
    resources :facilities, only: [:new, :create], controller: 'shops/facilities'
  end
  get '/shops/:shop_id/facilities/:id/events' => 'shops/facilities#events'
  resources :facilities, only: [:index, :show]
  resources :reservations, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :price
      get :dropin_spot
      get :spot
      post :confirm
      get :confirm
      post :credit_card
      get :thanks
    end
  end
  resource :personal_identification
  resources :dropin_reservations, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :plan
      get :dropin_spot
      post :confirm
      get :confirm
      post :credit_card
      get :thanks
    end
  end
  resources :plans
  resource :credit_card, only: [:new, :create, :show, :edit, :update]
  resources :invitations, only: [:index, :new, :create]
  resources :information, only: [:index, :show]

  post '/fetch_corporation_ids' => 'corporations#fetch_corporation_ids'

  namespace :corporation do
    get '/:corporation_token/users/new' => 'users#new', as: 'new_user'
    post '/:corporation_token/users' => 'users#create', as: 'user'
  end

  # 法人メニュー
  namespace :corporation_manage do
    root 'dashboards#index'
    resources :user_contracts
    resources :shops, only: %i[new show edit create update destroy] do
      resources :facilities, only: %i[new show edit create update destroy] do
        get :facility_events, on: :member
        resources :facility_keys, only: %i[new show edit create update destroy]
        resources :facility_temporary_plans, only: %i[index new edit create update destroy]
        resources :facility_temporary_plan_prices, only: %i[index]
        resources :facility_dropin_plans, only: %i[index new edit create update destroy]
        resources :facility_dropin_sub_plans, only: %i[index]
        resources :facility_pack_plans, only: %i[new edit create update destroy]
      end
    end
    resources :users do
      resources :personal_identifications, only: %i[new create edit update]
      member do
        post 'postal_matter_notification' => 'users#postal_matter_notification'
      end
    end
    resources :plans
    resources :user_corps
    resources :corporate_admin_users
    resources :billings, only: %i[index show]
    resources :reservations do
      post :payment, on: :collection
    end
    resources :dropin_reservations, only: %i[index show]
    resources :information
  end
end

app/controllers/admin/facilities_controller.rb
class Admin::FacilitiesController < AdminController
  before_action :set_corporation
  before_action :set_shop, except: [:events]
  before_action :set_facility, only: [:show, :edit, :update, :destroy]
  before_action :set_facility_pack_plans, only: [:show]

  def new
    @facility = @shop.facilities.new
  end

  def create
    @facility = @shop.facilities.new(facility_params)
    @facility.set_geocode
    @facility.set_chartered
    if @facility.save
      redirect_to [:admin, @corporation, @shop, @facility], notice: "#{Facility.model_name.human}を作成しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @facility.assign_attributes(facility_params)
    @facility.set_geocode
    @facility.set_chartered
    @facility.chartered_facilities.delete_all if !@facility.chartered
    if @facility.save
      redirect_to [:admin, @corporation, @shop, @facility], notice: "#{Facility.model_name.human}を更新しました。"
    else
      render :edit
    end
  end

  def show; end

  def destroy
    @facility.destroy!
    redirect_to admin_corporation_shop_path(@corporation, @shop), notice: "#{Facility.model_name.human}を削除しました"
  end

  def events
    @facility = Facility.find(params[:id])
    @reservations = @facility.reservations
  end

  private

  def set_corporation
    @corporation = Corporation.find(params[:corporation_id])
  end

  def set_shop
    @shop = @corporation.shops.find(params[:shop_id])
  end

  def set_facility
    @facility = @shop.facilities.find(params[:id])
  end

  def set_facility_pack_plans
    @q = @facility.facility_pack_plans.ransack(params[:q])
    @facility_pack_plans = @q.result(distinct: true)
  end

  def facility_params
    params.require(:facility).permit(
      :shop_id,
      :name,
      :image,
      :image_cache,
      :detail_document,
      :detail_document_cache,
      :description,
      :published,
      :max_num,
      :facility_type,
      :reservation_type,
      :address,
      :lat,
      :lon,
      :ks_room_id,
      :checkin_time_for_stay,
      :checkout_time_for_stay,
      :chartered,
      chartered_facilities_attributes: [:id, :facility_id, :child_facility_id, :_destroy],
      facility_plans_attributes: [:id, :plan_id, '_destroy']
    )
  end
end

app/controllers/corporation_manage/base.rb
class CorporationManage::Base < ApplicationController
  class AuthenticateCorporationError < StandardError; end
  layout 'corporation_manage/layouts/application'
  before_action :authenticate_corporation!

  rescue_from AuthenticateCorporationError, with: :corporation_not_authorized
  rescue_from ActiveRecord::DeleteRestrictionError, with: :can_not_delete

  private

  def authenticate_corporation!
    raise AuthenticateCorporationError unless current_user.present? && current_user.corporate_admin? && current_corporation?
  end

  def corporation_not_authorized
    redirect_to root_path, notice: 'アクセスできません'
  end
  
  def can_not_delete
    redirect_back fallback_location: root_path, notice: t('errors.messages.restrict_dependent_destroy.has_many')
  end
end

app/controllers/corporation_manage/billings_controller.rb
class CorporationManage::BillingsController < CorporationManage::Base

  def index
    set_default_year_month if params[:q].nil?
    @q = Billing.target_shops(current_corporation.shops.ids).ransack(params[:q])
    @billings = @q.result(distinct: true).page(params[:page])
  end

  def show
    @billing = Billing.find(params[:id])
    @billing_details = @billing.reservations.push(@billing.dropin_reservations)
  end

  private

  def set_default_year_month
    params[:q] = { year_month_eq: "#{Time.zone.now.last_month.year}/#{Time.zone.now.last_month.month}" }
  end
end

app/controllers/corporation_manage/corporate_admin_users_controller.rb
class CorporationManage::CorporateAdminUsersController < CorporationManage::Base
  before_action :set_corporate_admin_user, only: %i[show edit update destroy]

  def index
    @q = current_corporation.corporate_admin_users.ransack(params[:q])
    @corporate_admin_users = @q.result(distinct: true).order(id: :desc).page(params[:page])
  end

  def show; end

  def new
    @corporate_admin_user = current_corporation.corporate_admin_users.build
  end

  def edit; end

  def create
    @corporate_admin_user = current_corporation.corporate_admin_users.build(corporate_admin_user_params)
    if @corporate_admin_user.save
      redirect_to corporation_manage_corporate_admin_user_path(@corporate_admin_user), notice: t('common.messages.created', name: CorporateAdminUser.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @corporate_admin_user.update(corporate_admin_user_params)
      redirect_to corporation_manage_corporate_admin_user_path(@corporate_admin_user), notice: t('common.messages.updated', name: CorporateAdminUser.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @corporate_admin_user.destroy!
    redirect_to corporation_manage_corporate_admin_users_path, notice: t('common.messages.deleted', name: CorporateAdminUser.model_name.human)
  end

  private

  def set_corporate_admin_user
    @corporate_admin_user = current_corporation.corporate_admin_users.find(params[:id])
  end

  def corporate_admin_user_params
    params.require(:corporate_admin_user).permit(
      :email,
      :name,
      :tel,
      :password,
      :password_confirmation
    ).merge(advertise_notice_flag: false,
            user_type: :corporate_admin,
            payway: :invoice,
            state: :registered,
            corporation_ids: [current_corporation.id])
  end
end

app/controllers/corporation_manage/dashboards_controller.rb
class CorporationManage::DashboardsController < CorporationManage::Base
  def index
    @shops = current_corporation.shops.order(id: :desc).page(params[:page])
  end
end

app/controllers/corporation_manage/dropin_reservations_controller.rb
class CorporationManage::DropinReservationsController < CorporationManage::Base
  def index
    @q = DropinReservation.with_corporation(current_corporation).ransack(params[:q])
    @dropin_reservations = @q.result.order(checkin: :desc)
    respond_to do |format|
      format.html do
        @dropin_reservations = @dropin_reservations.page(params[:page]).per(30)
      end
      format.csv do
        send_data @dropin_reservations.to_csv(col_sep: "\t"), filename: t('common.csv.dropin_reservation_csv', date: Time.zone.now.strftime('%Y/%m/%d'))
      end
    end
  end
  
  def show
    @dropin_reservation = DropinReservation.find(params[:id])
  end
end

app/controllers/corporation_manage/facilities_controller.rb
class CorporationManage::FacilitiesController < CorporationManage::Base
  before_action :set_shop
  before_action :set_facility, only: %i[show edit update destroy facility_events]
  before_action :set_facility_pack_plans, only: [:show]

  def show
    gon.schedular_licence_key = ENV['SCHEDULER_LICENCE_KEY']
    gon.shop_id = @shop.id
    gon.opening_time = @shop.opening_time
    gon.closing_time = @shop.closing_time
    gon.facility_id = @facility.id
  end

  def new
    @facility = @shop.facilities.build
  end

  def create
    @facility = @shop.facilities.build(facility_params)
    @facility.set_geocode
    @facility.set_chartered
    if @facility.save
      redirect_to corporation_manage_shop_facility_path(@shop, @facility), notice: t('common.messages.created', name: Facility.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @facility.assign_attributes(facility_params)
    @facility.set_geocode
    @facility.set_chartered
    @facility.chartered_facilities.delete_all if !@facility.chartered
    if @facility.save
      redirect_to corporation_manage_shop_facility_path(@shop, @facility), notice: t('common.messages.updated', name: Facility.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @facility.destroy!
    redirect_to corporation_manage_shop_path(@shop), notice: t('common.messages.deleted', name: Facility.model_name.human)
  end

  # GET /corporation_manager/shops/:shop_id/facilities/:facility_id/facility_events (format: json)
  def facility_events
    @reservations = @facility.reservations
  end

  private

  def set_shop
    @shop = current_corporation.shops.find(params[:shop_id])
  end

  def set_facility
    @facility = @shop.facilities.find(params[:id])
  end

  def set_facility_pack_plans
    @q = @facility.facility_pack_plans.ransack(params[:q])
    @facility_pack_plans = @q.result(distinct: true)
  end

  def facility_params
    params.require(:facility).permit(
      :shop_id,
      :name,
      :image,
      :image_cache,
      :detail_document,
      :detail_document_cache,
      :description,
      :published,
      :max_num,
      :facility_type,
      :reservation_type,
      :address,
      :lat,
      :lon,
      :ks_room_id,
      :checkin_time_for_stay,
      :checkout_time_for_stay,
      :chartered,
      chartered_facilities_attributes: [:id, :facility_id, :child_facility_id, :_destroy],
      facility_plans_attributes: [:id, :plan_id, :_destroy]
    )
  end
end

app/controllers/corporation_manage/facility_dropin_plans_controller.rb
class CorporationManage::FacilityDropinPlansController < CorporationManage::Base
  before_action :set_facility
  before_action :set_facility_dropin_plan, only: %i[edit update destroy]

  def index
    @facility_dropin_plans = @facility.facility_dropin_plans
  end

  def new
    @facility_dropin_plan = @facility.facility_dropin_plans.build
  end

  def create
    @facility_dropin_plan = @facility.facility_dropin_plans.build(facility_dropin_plan_params)
    if @facility_dropin_plan.save
      redirect_to corporation_manage_shop_facility_path(@facility.shop, @facility),
                  notice: t('common.messages.created', name: FacilityDropinPlan.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @facility_dropin_plan.update(facility_dropin_plan_params)
      redirect_to corporation_manage_shop_facility_path(@facility.shop, @facility),
                  notice: t('common.messages.updated', name: FacilityDropinPlan.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @facility_dropin_plan.destroy!
    redirect_to corporation_manage_shop_facility_path(@facility.shop, @facility),
                notice: t('common.messages.deleted', name: FacilityDropinPlan.model_name.human)
  end

  private

  def set_facility
    @facility = Facility.belongs_to_corporation(current_corporation).find(params[:facility_id])
  end

  def set_facility_dropin_plan
    @facility_dropin_plan = @facility.facility_dropin_plans.find(params[:id])
  end

  def facility_dropin_plan_params
    params.require(:facility_dropin_plan).permit(
      :plan_id,
      :guide_mail_title,
      :guide_mail_content,
      :guide_file,
      facility_dropin_sub_plans_attributes: [
        :id,
        :facility_dropin_plan_id,
        :name,
        :starting_time,
        :ending_time,
        :price,
        :_destroy
      ]
    )
  end
end

app/controllers/corporation_manage/facility_dropin_sub_plans_controller.rb
class CorporationManage::FacilityDropinSubPlansController < CorporationManage::Base
  def index
    @facility = Facility.belongs_to_corporation(current_corporation).find(params[:facility_id])
    @facility_dropin_sub_plans = @facility.facility_dropin_sub_plans
  end
end

app/controllers/corporation_manage/facility_temporary_plan_prices_controller.rb
class CorporationManage::FacilityTemporaryPlanPricesController < CorporationManage::Base
  def index
    @shop = current_corporation.shops.find(params[:shop_id])
    @facility = @shop.facilities.find(params[:facility_id])
    @facility_temporary_plans = @facility.facility_temporary_plans
    @facility_temporary_plan_prices = @facility.facility_temporary_plan_prices
  end
end

app/views/corporation_manage/facilities/_chartered_facility_fields.html.erb
<% facility_list = Facility
                  .joins(:shop)
                  .where(shops: { corporation_id: current_corporation.id })
                  .where.not(chartered: true)
                  .map{|f| [f.name, f.id]} %>

<div class='row'>
  <div class='nested-fields form-inline'>
    <div class='control-label col-sm-2'>
      <label>貸し切るスペース</label>
    </div>
    <div class='col-sm-10'>
      <%= f.select :child_facility_id,
        facility_list, hide_label: true %>
      <%= link_to_remove_association "行削除",
        f, class: 'ml15 btn btn-danger' %>
    </div>
  </div>
</div>

app/views/corporation_manage/facilities/_facility_dropin_plans.html.erb
<div class="box box-default">
  <div class="box-header with-border">
    <h4 class="box-title"><%= FacilityDropinPlan.model_name.human %></h4>
    <div class="box-tools cy-add-dropin-plan-btn">
      <%= link_to t('common.btn.new'),
                  new_corporation_manage_shop_facility_facility_dropin_plan_path(shop, facility),
                  class: 'btn btn-primary' %>
    </div>
  </div>
  <div id="js-dropin-plan-table"></div>
</div>

app/views/corporation_manage/facilities/_facility_pack_plan.html.erb
<!-- パック料金対象プラン -->
<% url_options = { action: :show } %>
<% html_options = { remote: true, method: :get } %>

<div class="box box-default">
  <div class="box-header with-border">
    <h4 class="box-title">パック料金対象プラン</h4>
    <div class="box-tools">
      <%= link_to "新規追加", new_corporation_manage_shop_facility_facility_pack_plan_path(shop, facility), class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="pack_plans">
    <table class="table">
      <thead>
        <tr>
          <th><%= sort_link(q, :name, '適用プラン名', url_options, html_options) %></th>
          <th><%= sort_link(q, :unit_time, '時間', url_options, html_options) %></th>
          <th><%= sort_link(q, :unit_price, '単価(税抜)', url_options, html_options) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if facility_pack_plans.present? %>
          <% facility_pack_plans.each do |pack_plan| %>
            <tr>
              <td><%= pack_plan.plan.try(:name) || '非会員' %></td>
              <td><%= pack_plan.unit_time %>時間</td>
              <td><%= delimiter_price(pack_plan.unit_price) %></td>
              <td>
                <%= link_to '編集', edit_corporation_manage_shop_facility_facility_pack_plan_path(shop, facility, pack_plan), class: 'btn btn-sm btn-primary' %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/corporation_manage/facilities/_facility_temporary_plan.html.erb
<div class="box box-default">
  <div class="box-header with-border">
    <h4 class="box-title"><%= FacilityTemporaryPlan.model_name.human %></h4>
    <div class="box-tools cy-add-temporary-plan-btn">
      <%= link_to t('common.btn.new'), new_corporation_manage_shop_facility_facility_temporary_plan_path(shop, facility), class: 'btn btn-primary' %>
    </div>
  </div>
  <div id="js-temporary-plan-table"></div>
</div>

app/views/corporation_manage/facilities/_form.html.erb
<%= bootstrap_nested_form_for([:corporation_manage, shop, facility], layout: :horizontal) do |f| %>
  <%= f.text_field :name, placeholder: t('.add_name') %>
  <%= f.number_field :max_num %>
  <%= f.text_field :address, placeholder: t('.add_address') %>

  <%= f.select :facility_type, Facility.facility_types_i18n.invert,
    {}, {prompt: t('.add_facility_type'), onchange: 'displayFormForStay();', class: 'facility-type'} %>

  <div class="option_form" id="for_stay" style="display: none;">
    <%= f.time_field :checkin_time_for_stay %>
    <%= f.time_field :checkout_time_for_stay %>
  </div>

  <%# 貸し切り対応フォーム %>
  <div class='option_form' id='chartered_area' style= "display: <%= f.object.chartered ? 'block;' : 'none;' %>">
    <div class='form-group'>
      <div class='control-label col-sm-2'>
        <label>貸し切り施設</label>
      </div>
      <div class='col-sm-10 form-inline text-left'>
        <%= link_to_add_association '行を追加',
          f, :chartered_facilities,
          data: {association_insertion_node: '#chartered_facilities'},
          class: 'btn btn-success mb15' %>
      </div>
    </div>
    <div id='chartered_facilities'>
      <%= f.fields_for :chartered_facilities do |cf| %>
        <%= render 'chartered_facility_fields', f: cf %>
      <% end %>
    </div>
  </div>

  <%= f.file_field :image, class: 'mt15' %>
  <%= f.hidden_field :image_cache %>
  <%= f.text_field :ks_room_id %>
  <%= f.text_area :description, rows: 6 %>
  <div class='form-group'>
    <div class='control-label col-sm-2'>
      <label><%= Facility.human_attribute_name(:published) %></label>
    </div>
    <div class='col-sm-10 form-inline'>
      <%= f.radio_button :published, true  %><span class='ml10'>掲載する</span>
      <%= f.radio_button :published, false %><span class='ml10'>掲載しない</span>
    </div>
  </div>

  <%= f.select :reservation_type, Facility.reservation_types_i18n.invert,
    include_blank: 'この施設の予約方法を選択' %>

  <div class='row'>
  <%= f.form_group :facility_plans, label: {text: t('.target_plan')} do %>
    <%= f.fields_for :facility_plans do |fp| %>
      <div class="form-inline cy-facility-plans">
        <%= fp.collection_select :plan_id,
                                  current_corporation.plans,
                                  :id,
                                  :name,
                                  { prompt: t('.select_plan'),
                                    hide_label: true },
                                  class: 'add-link-column cy-select-plan',
                                  inline: true %>
        <%= fp.link_to_remove t('common.btn.delete'),
                              class: 'glyphicon glyphicon-remove',
                              inline: true %>
      </div>
    <% end %>
    <%= f.link_to_add t('.add_plan'), :facility_plans,
      class: 'btn btn-info glyphicon glyphicon-plus cy-add-plan' %>
  <% end %>
  </div>

  <%= f.submit class: 'btn btn-primary center-block pull-right' %>
<% end %>

app/views/corporation_manage/facilities/edit.html.erb
<div class="box box-default">
  <div class="box-body">
    <%= render 'form', shop: @shop, facility: @facility %>
  </div>
</div>

app/views/corporation_manage/facilities/new.html.erb
<div class="box box-default">
  <div class="box-body">
    <%= render 'form', shop: @shop, facility: @facility %>
  </div>
</div>

app/views/corporation_manage/facilities/show.html.erb
<div class="box box-default">
  <div class="box-header with-border">
    <div class="box-tools cy-facility-box-tools">
      <%= link_to t('common.btn.back'), corporation_manage_shop_path(@shop), class: 'btn btn-default' %>
      <%= link_to t('common.btn.edit'), edit_corporation_manage_shop_facility_path(@shop, @facility), class: 'btn btn-primary' %>
      <%= link_to t('common.btn.delete'),
                  corporation_manage_shop_facility_path(@shop, @facility),
                  method: :delete,
                  data: { confirm: t('common.confirms.really_to_delete') },
                  class: 'btn btn-danger' %>
    </div>
  </div>
  <div class="box-body">
    <table class="table table-striped">
      <tr class="cy-facility-name">
        <th><%= Facility.human_attribute_name(:id) %></th>
        <td><%= @facility.id %></td>
      </tr>
      <tr class="cy-facility-name">
        <th><%= Facility.human_attribute_name(:name) %></th>
        <td><%= @facility.name %></td>
      </tr>
      <tr class="cy-facility-max-num">
        <th><%= Facility.human_attribute_name(:max_num) %></th>
        <td><%= @facility.max_num %></td>
      </tr>
      <tr class="cy-facility-address">
        <th><%= Facility.human_attribute_name(:address) %></th>
        <td><%= @facility.address %></td>
      </tr>
      <tr class="cy-facility-type">
        <th><%= Facility.human_attribute_name(:facility_type) %></th>
        <td><%= @facility.facility_type_i18n %></td>
      </tr>
      <% if @facility.facility_type == "accommodation" %>
        <tr>
          <th><%= Facility.human_attribute_name(:checkin_time_for_stay) %></th>
          <td><%= @facility.checkin_time_for_stay.strftime("%H:%M") %></td>
        </tr>
        <tr>
          <th><%= Facility.human_attribute_name(:checkout_time_for_stay) %></th>
          <td><%= @facility.checkout_time_for_stay.strftime("%H:%M") %></td>
        </tr>
      <% end %>
      <tr>
        <th><%= Facility.human_attribute_name(:image) %></th>
        <td><%= image_tag @facility.image.main.url, width: "374px" %></td>
      </tr>
      <tr class="cy-facility-description">
        <th><%= Facility.human_attribute_name(:description) %></th>
        <td><%= simple_format @facility.description %></td>
      </tr>
      <tr class="cy-facility-description">
        <th><%= Facility.human_attribute_name(:chartered) %></th>
        <td><%= @facility.chartered ? '貸し切り対応中' : '貸し切り非対応' %></td>
      </tr>
      <% if @facility.chartered? %>
        <th>貸し切り紐付け施設</th>
        <td>
        <% @facility.associated_facilities.each do |facility| %>
          <%= "#{facility.name} ,  " %>
        <% end %>
        </td>
      <% end %>
      <tr class="cy-facility-description">
        <th><%= Facility.human_attribute_name(:published) %></th>
        <td><%= @facility.published ? '掲載中' : '掲載停止中' %></td>
      </tr>
      <tr class="cy-facility-description">
        <th><%= Facility.human_attribute_name(:reservation_type) %></th>
        <td><%= @facility.reservation_type_i18n %></td>
      </tr>
      <tr class="cy-facility-plans">
        <th><%= t('.target_plan') %></th>
        <td>
          <% @facility.plans.each do |plan| %>
            <%= plan.name %><br>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>

<div class="box box-default">
  <div class="box-header with-border">
    <h4 class="box-title"><%= t('.facility_key_index') %></h4>
    <div class="box-tools">
      <%= link_to t('common.btn.new'), new_corporation_manage_shop_facility_facility_key_path(@shop, @facility), class: 'btn btn-primary cy-add-facility-key' %>
    </div>
  </div>
  <div class="box-body">
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= FacilityKey.human_attribute_name(:name) %></th>
        <th><%= FacilityKey.human_attribute_name(:password) %></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @facility.facility_keys.each do |key| %>
        <tr>
          <td><%= key.name %></td>
          <td><%= key.password %></td>
          <td>
            <%= link_to t('common.btn.show'), corporation_manage_shop_facility_facility_key_path(@shop, @facility, key), class: 'btn btn-default' %>
            <%= link_to t('common.btn.edit'), edit_corporation_manage_shop_facility_facility_key_path(@shop, @facility, key), class: 'btn btn-primary' %>
            <%= link_to t('common.btn.delete'),
                        corporation_manage_shop_facility_facility_key_path(@shop, @facility, key),
                        method: :delete,
                        data: { confirm: t('common.confirms.really_to_delete') },
                        class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="box box-default">
  <div class="box-header with-border">
    <h4 class="box-title"><%= t('.reservation_calendar') %></h4>
  </div>
  <div id="js-reservation-calendar"></div>
</div>

<% case @facility.facility_type %>
<% when 'dropin' %>
  <%= render 'facility_dropin_plans', shop: @shop, facility: @facility %>
<% when 'accommodation' %>
  <%= render 'facility_temporary_plan', shop: @shop, facility: @facility %>
<% else %>
  <%= render 'facility_temporary_plan', shop: @shop, facility: @facility %>
  <div id="facility_pack_plan">
    <%= render 'facility_pack_plan', shop: @shop, facility: @facility, facility_pack_plans: @facility_pack_plans, q: @q %>
  </div>
<% end %>

app/views/corporation_manage/facilities/show.js.erb
$('#facility_pack_plan').html('<%= j render partial: "facility_pack_plan", locals: { shop: @shop, facility: @facility, q: @q, facility_pack_plans: @facility_pack_plans } %>');